name: Publish package to the Maven Central Repository and GitHub Packages
on:
  release:
    types: [created]
  push:
    branches: [ feature/github-mvn-repository ]
  pull_request:
    branches: [ feature/github-mvn-repository ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_REPOSITORY }}
        run: mvn deploy -Dregistry=https://maven.pkg.github.com/TFG-IDEAS-PLANTUML/ideas-base-module/
